=== Limoelou/DSB-project/struct.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT dsb (account+,accountBanned,characters+,maps+,purchases+,weapons+)>
<!ELEMENT account (Id,Username,Password,Lootbox,Gold,Level,Rank)>
<!ELEMENT accountBanned (Username,BanDate,Reason)>
<!ELEMENT characters (Id,Name,LifePoints,Armor,MapId,SkinId,WeaponId,Shield)>
<!ELEMENT maps (MapId,Name,Type)>
<!ELEMENT purchases (Username,Date,LootboxNumber)>
<!ELEMENT weapons (WeaponId,Name,CanHeadshot,IsMelee,Magazine,DamagePerHit,FireRate,HealRate)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT Lootbox (#PCDATA)>
<!ELEMENT Gold (#PCDATA)>
<!ELEMENT Level (#PCDATA)>
<!ELEMENT Rank (#PCDATA)>
<!ELEMENT BanDate (#PCDATA)>
<!ELEMENT Reason (#PCDATA)>
<!ELEMENT LifePoints (#PCDATA)>
<!ELEMENT Armor (#PCDATA)>
<!ELEMENT SkinId (#PCDATA)>
<!ELEMENT Shield (#PCDATA)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT LootboxNumber (#PCDATA)>
<!ELEMENT CanHeadshot (#PCDATA)>
<!ELEMENT IsMelee (#PCDATA)>
<!ELEMENT Magazine (#PCDATA)>
<!ELEMENT DamagePerHit (#PCDATA)>
<!ELEMENT FireRate (#PCDATA)>
<!ELEMENT HealRate (#PCDATA)>
<!ELEMENT Id (#PCDATA)>
<!ELEMENT Username (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT MapId (#PCDATA)>
<!ELEMENT WeaponId (#PCDATA)>

=== Limoelou/DSB-project/database.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE dsb SYSTEM "struct.dtd"><dsb><account><Id>1</Id><Username>Limoelou</Username><Password>Limouiled</Password><Lootbox>150</Lootbox><Gold>5000</Gold><Level>456</Level><Rank>DoudouMasta</Rank></account><account><Id>2</Id><Username>Skinz</Username><Password>Mandoled</Password><Lootbox>8</Lootbox><Gold>3</Gold><Level>6000</Level><Rank>GrandMandol</Rank></account><account><Id>3</Id><Username>Jacket</Username><Password>MelenFarmer</Password><Lootbox>0</Lootbox><Gold>60000</Gold><Level>890</Level><Rank>GenjiOTP</Rank></account><account><Id>4</Id><Username>Patrick</Username><Password>Sebastien</Password><Lootbox>39</Lootbox><Gold>9</Gold><Level>39</Level><Rank>Gold</Rank></account><account><Id>5</Id><Username>Simon</Username><Password>lePetitPrincedu69</Password><Lootbox>4</Lootbox><Gold>499</Gold><Level>49</Level><Rank>Grand Master</Rank></account><account><Id>6</Id><Username>Francois</Username><Password>asiatique</Password><Lootbox>1</Lootbox><Gold>1</Gold><Level>1385</Level><Rank>Paper</Rank></account><account><Id>7</Id><Username>simon</Username><Password>petitjoyeux</Password><Lootbox>3</Lootbox><Gold>398321</Gold><Level>39</Level><Rank>Gold</Rank></account><accountBanned><Username>Jacket</Username><BanDate>2019-03-04</BanDate><Reason>Toxicity</Reason></accountBanned><characters><Id>1</Id><Name>Soldier 76</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>1</MapId><SkinId>1</SkinId><WeaponId>1</WeaponId><Shield>0</Shield></characters><characters><Id>2</Id><Name>Tracer</Name><LifePoints>150</LifePoints><Armor>0</Armor><MapId>1</MapId><SkinId>0</SkinId><WeaponId>2</WeaponId><Shield>0</Shield></characters><characters><Id>3</Id><Name>Hanzo</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>1</MapId><SkinId>1</SkinId><WeaponId>3</WeaponId><Shield>0</Shield></characters><characters><Id>4</Id><Name>Widowmaker</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>1</MapId><SkinId>1</SkinId><WeaponId>4</WeaponId><Shield>0</Shield></characters><characters><Id>5</Id><Name>Mercy</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>1</MapId><SkinId>1</SkinId><WeaponId>5</WeaponId><Shield>0</Shield></characters><characters><Id>6</Id><Name>Ashe</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>1</MapId><SkinId>1</SkinId><WeaponId>7</WeaponId><Shield>0</Shield></characters><characters><Id>7</Id><Name>Bastion</Name><LifePoints>200</LifePoints><Armor>100</Armor><MapId>2</MapId><SkinId>0</SkinId><WeaponId>9</WeaponId><Shield>0</Shield></characters><characters><Id>8</Id><Name>Baptiste</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>1</MapId><SkinId>0</SkinId><WeaponId>8</WeaponId><Shield>0</Shield></characters><characters><Id>9</Id><Name>Genji</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>4</MapId><SkinId>0</SkinId><WeaponId>6</WeaponId><Shield>0</Shield></characters><characters><Id>10</Id><Name>Orisa</Name><LifePoints>200</LifePoints><Armor>200</Armor><MapId>4</MapId><SkinId>3</SkinId><WeaponId>10</WeaponId><Shield>0</Shield></characters><characters><Id>11</Id><Name>D.Va</Name><LifePoints>400</LifePoints><Armor>200</Armor><MapId>2</MapId><SkinId>1</SkinId><WeaponId>11</WeaponId><Shield>0</Shield></characters><characters><Id>12</Id><Name>Reinhardt</Name><LifePoints>300</LifePoints><Armor>200</Armor><MapId>2</MapId><SkinId>2</SkinId><WeaponId>12</WeaponId><Shield>0</Shield></characters><characters><Id>13</Id><Name>Roadhog</Name><LifePoints>600</LifePoints><Armor>0</Armor><MapId>2</MapId><SkinId>1</SkinId><WeaponId>13</WeaponId><Shield>0</Shield></characters><characters><Id>14</Id><Name>Winston</Name><LifePoints>400</LifePoints><Armor>100</Armor><MapId>3</MapId><SkinId>2</SkinId><WeaponId>14</WeaponId><Shield>0</Shield></characters><characters><Id>15</Id><Name>Wrecking Ba</Name><LifePoints>500</LifePoints><Armor>600</Armor><MapId>3</MapId><SkinId>2</SkinId><WeaponId>15</WeaponId><Shield>0</Shield></characters><characters><Id>16</Id><Name>Zarya</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>3</MapId><SkinId>0</SkinId><WeaponId>16</WeaponId><Shield>200</Shield></characters><characters><Id>17</Id><Name>Doomfist</Name><LifePoints>250</LifePoints><Armor>0</Armor><MapId>4</MapId><SkinId>0</SkinId><WeaponId>17</WeaponId><Shield>0</Shield></characters><characters><Id>18</Id><Name>Junkrat</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>3</MapId><SkinId>2</SkinId><WeaponId>18</WeaponId><Shield>0</Shield></characters><characters><Id>19</Id><Name>McCree</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>3</MapId><SkinId>0</SkinId><WeaponId>19</WeaponId><Shield>0</Shield></characters><characters><Id>20</Id><Name>Mei</Name><LifePoints>250</LifePoints><Armor>0</Armor><MapId>4</MapId><SkinId>1</SkinId><WeaponId>20</WeaponId><Shield>0</Shield></characters><characters><Id>21</Id><Name>Pharah</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>4</MapId><SkinId>1</SkinId><WeaponId>21</WeaponId><Shield>0</Shield></characters><characters><Id>22</Id><Name>Reaper</Name><LifePoints>250</LifePoints><Armor>0</Armor><MapId>4</MapId><SkinId>4</SkinId><WeaponId>22</WeaponId><Shield>0</Shield></characters><characters><Id>23</Id><Name>Sombra</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>20</MapId><SkinId>0</SkinId><WeaponId>23</WeaponId><Shield>0</Shield></characters><characters><Id>24</Id><Name>Symmetra</Name><LifePoints>100</LifePoints><Armor>0</Armor><MapId>5</MapId><SkinId>0</SkinId><WeaponId>24</WeaponId><Shield>100</Shield></characters><characters><Id>25</Id><Name>Torbjorn</Name><LifePoints>200</LifePoints><Armor>50</Armor><MapId>6</MapId><SkinId>4</SkinId><WeaponId>25</WeaponId><Shield>0</Shield></characters><characters><Id>26</Id><Name>Ana</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>7</MapId><SkinId>0</SkinId><WeaponId>26</WeaponId><Shield>0</Shield></characters><characters><Id>27</Id><Name>Brigitte</Name><LifePoints>200</LifePoints><Armor>50</Armor><MapId>8</MapId><SkinId>0</SkinId><WeaponId>27</WeaponId><Shield>0</Shield></characters><characters><Id>28</Id><Name>Lucio</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>9</MapId><SkinId>1</SkinId><WeaponId>28</WeaponId><Shield>0</Shield></characters><characters><Id>29</Id><Name>Moira</Name><LifePoints>200</LifePoints><Armor>0</Armor><MapId>10</MapId><SkinId>1</SkinId><WeaponId>29</WeaponId><Shield>0</Shield></characters><characters><Id>30</Id><Name>Zenyatta</Name><LifePoints>50</LifePoints><Armor>0</Armor><MapId>10</MapId><SkinId>1</SkinId><WeaponId>30</WeaponId><Shield>150</Shield></characters><maps><MapId>1</MapId><Name>Rialto</Name><Type>Escort</Type></maps><maps><MapId>2</MapId><Name>Numbani</Name><Type>Hybrid</Type></maps><maps><MapId>3</MapId><Name>Hanamura</Name><Type>Assault</Type></maps><maps><MapId>4</MapId><Name>Horizon Lunar Colony</Name><Type>Assault</Type></maps><maps><MapId>5</MapId><Name>Route 66</Name><Type>Escort</Type></maps><maps><MapId>6</MapId><Name>Gibraltar</Name><Type>Escort</Type></maps><maps><MapId>7</MapId><Name>Busan</Name><Type>Control</Type></maps><maps><MapId>8</MapId><Name>King's Row </Name><Type>Hybrid</Type></maps><maps><MapId>9</MapId><Name>Oasis</Name><Type>Control</Type></maps><maps><MapId>10</MapId><Name>Dorado</Name><Type>Escort</Type></maps><maps><MapId>11</MapId><Name>Ilios </Name><Type>Control</Type></maps><maps><MapId>12</MapId><Name>Lijiang Tower</Name><Type>Control</Type></maps><maps><MapId>13</MapId><Name>Junkertown</Name><Type>Escort</Type></maps><maps><MapId>14</MapId><Name>Volskaya industries</Name><Type>Assault</Type></maps><maps><MapId>15</MapId><Name>Temple of Anubis</Name><Type>Assault</Type></maps><maps><MapId>16</MapId><Name>Paris</Name><Type>Assault</Type></maps><maps><MapId>17</MapId><Name>Blizzard World</Name><Type>Hybrid</Type></maps><maps><MapId>18</MapId><Name>Nepal</Name><Type>Control</Type></maps><maps><MapId>19</MapId><Name>Eichenwalde</Name><Type>Hybrid</Type></maps><maps><MapId>20</MapId><Name>Hollywood</Name><Type>Hybrid</Type></maps><maps><MapId>21</MapId><Name>Ayutthaya</Name><Type>Arcade</Type></maps><maps><MapId>22</MapId><Name>Black Forest</Name><Type>Arcade</Type></maps><maps><MapId>23</MapId><Name>Castillo</Name><Type>Arcade</Type></maps><maps><MapId>24</MapId><Name>Chateau Guillard</Name><Type>Arcade</Type></maps><maps><MapId>25</MapId><Name>Ecopoint : Antarctica</Name><Type>Arcade</Type></maps><maps><MapId>26</MapId><Name>Necropolis</Name><Type>Arcade</Type></maps><maps><MapId>27</MapId><Name>Petra</Name><Type>Arcade</Type></maps><purchases><Username>Limoelou</Username><Date>2015-05-13</Date><LootboxNumber>5</LootboxNumber></purchases><purchases><Username>Jacket</Username><Date>2019-03-22</Date><LootboxNumber>6</LootboxNumber></purchases><purchases><Username>Jacket</Username><Date>2019-03-23</Date><LootboxNumber>23</LootboxNumber></purchases><purchases><Username>Limoelou</Username><Date>2019-03-17</Date><LootboxNumber>19</LootboxNumber></purchases><purchases><Username>Skinz</Username><Date>2019-03-24</Date><LootboxNumber>9</LootboxNumber></purchases><purchases><Username>Skinz</Username><Date>2019-03-19</Date><LootboxNumber>5</LootboxNumber></purchases><weapons><WeaponId>1</WeaponId><Name>Pulse Rifle</Name><CanHeadshot>1</CanHeadshot><IsMelee>0</IsMelee><Magazine>25</Magazine><DamagePerHit>20</DamagePerHit><FireRate>9</FireRate><HealRate/></weapons><weapons><WeaponId>2</WeaponId><Name>Pulse Pistols</Name><CanHeadshot>1</CanHeadshot><IsMelee>0</IsMelee><Magazine>40</Magazine><DamagePerHit>6</DamagePerHit><FireRate>20</FireRate><HealRate/></weapons><weapons><WeaponId>3</WeaponId><Name>Storm Bow</Name><CanHeadshot>1</CanHeadshot><IsMelee>0</IsMelee><Magazine/><DamagePerHit>125</DamagePerHit><FireRate>20</FireRate><HealRate/></weapons><weapons><WeaponId>4</WeaponId><Name>Widow's kiss</Name><CanHeadshot>1</CanHeadshot><IsMelee>0</IsMelee><Magazine>30</Magazine><DamagePerHit>125</DamagePerHit><FireRate>9</FireRate><HealRate/></weapons><weapons><WeaponId>5</WeaponId><Name>Caduceus Staff</Nam
